### ISSUE TITLE
Question: remove_small_buildings function still available?

### ISSUE THREAD

**Issue by JSchiefelbein** [RWTH-EBC/uesgraphs#3]
The usegraphs pre-release hat an example_osm.py script with a function to remove buildings with a ground area smaller than min_area value. pyCity_calc osm_call and city_generator used this function. Is it still available respectively moved/renamed...?
If not, where would you place this function/method? 
Within uesgraphs or within a(ny) pyCity addon?

```Python
def remove_small_buildings(input_graph, min_area):
    """Removes all buildings from the graph that have area less than `min_area`

    Parameters
    ----------
    input_graph : uesgraphs.uesgraph.UESGraph object
        An UESGraph that will be analysed for data
    min_area : float
        Minimum area for a building to remain in the graph

    Returns
    -------
    input_graph : uesgraphs.uesgraph.UESGraph object
        An UESGraph that will be analysed for data
    """
    to_remove = []
    for building in input_graph.nodelist_building:
        if 'area' in input_graph.node[building]:
            if input_graph.node[building]['area'] <= min_area:
                to_remove.append(building)

    for building in to_remove:
        input_graph.remove_building(building)
```

**Comment by marcusfuchs** [comment]
@JSchiefelbein I did not include this function in the release, because I thought it may be a bit too special for a general release and I did not have time to work through the osm example and make it ready for the release. If that would work for you, I'd suggest to include the function in pyCity where it's needed.

**Comment by JSchiefelbein** [comment]
@marcusfuchs that's fine with me. Going to close this issue.
