### ISSUE TITLE
Bug in visuals buildings

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/uesgraphs#5]
I think this might be a bug in the visualization function of the building nodes. If labels "building" is served, the visuals function works and plots the node number as text. Serving the label "name", uses some neighbors functions / methods which i can't find and is leading to an error. Should we replace maybe the labels of plotting the building name to "building_name" and then just use the same text placement as in the "building" node text placing method?

**Comment by MichaMans** [comment]
Arrg sorry. Might be the python 3.5/3.6 thing. I'll have a look

**Comment by MichaMans** [comment]
Mhh update: It wasn't the python version which leads to IndexError. I think it is that there are no connections between the buildings and or that the buildings are not connected with each other. So visuals only seems to work with a complete graph.?

**Comment by marcusfuchs** [comment]
While some functions in the visuals module will work with almost any graph, it is very likely that some functions only cover a small range of use cases.
