### ISSUE TITLE
Bug in add_network_node?

### ISSUE THREAD

**Issue by jsc-tbe** [RWTH-EBC/uesgraphs#6]
The function ``add_node()`` of the networkX graph requires the argument 'n' but in ``add_network_node()`` only the argument 'node_for_adding=node_number' is passed. This leads to the `TypeError: add_node() missing 1 required positional argument: 'n' `.

To solve this we should try
```python
add_node(node_number)
```
or
```python
add_node(n=node_number)
```

**Comment by jsc-tbe** [comment]
See lines 274, 353, 471, 485 in uesgraphs.py

**Comment by marcusfuchs** [comment]
@jsc-tbe Are you sure you are using the latest version of networkx? Could you try to update networkx and try again?

**Comment by jsc-tbe** [comment]
Oh sorry @marcusfuchs, my fault. You are right, I used an old networkX version. Now it works. Thanks

**Comment by jsc-tbe** [comment]
Maybe we can set a minimal version number of networkX in the setup file, so there won't be any problems with wrong verisons.

**Comment by marcusfuchs** [comment]
Yes, that is a good idea!
